on:
  pull_request:
  push:

jobs:
  version:
    uses: noveto-com/shared-workflows/.github/workflows/version.yml@develop

  docs:
    needs: version
    uses: noveto-com/shared-workflows/.github/workflows/docs.yml@develop
    with:
      version: ${{ needs.version.outputs.version }}
      pdf-name: "sharedworkflows.pdf"
      dependencies: "Sphinx==3.5.4 myst-parser==0.15.2"

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: [version, docs]
    uses: noveto-com/shared-workflows/.github/workflows/deploy-s3.yml@develop
    with:
      version: ${{ needs.version.outputs.version }}
      project: shared-workflows
    secrets:
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
