on:
  pull_request:
  push:
    # branches:
    #   - master

jobs:
  version:
    uses: noveto-com/shared-workflows/.github/workflows/version.yml@main

  docs:
    needs: version
    uses: noveto-com/shared-workflows/.github/workflows/docs.yml@develop
    with:
      version: ${{ needs.version.outputs.version }}
      pdf-name: "sharedworkflows.pdf"
      dependencies: "Sphinx==3.5.4 myst-parser==0.15.2"
